### ISSUE TITLE
Pourquoi je suis inscrit?

### ISSUE THREAD

**Issue by dtarcz** [Simplon-Narbonne/wiki2017#1]
Salut salut,
j'imagine ne pas être le seul, alors je pose la question pour tout ceux qui se la pose :)
## Pourquoi je suis inscrit ici? 

Puis-je participer à écrire ce Readme? 
Et va t-il s'agir de relater les 6 mois de formation?

En gros, on fait quoi de ça? hahaha.

**Comment by Boyquotes** [comment]
Salut,

Il me semble que tu as fais la promo 1 c'est pour cela que tu es inscrit ;)

Il va relater les "8" mois de formation oui, participer malheureusement(ou heursement) n'étant pas présent tu ne peux pas apporter ta pierre à l'édifice, au mieux corriger mes fautes d'orthographes...

Mais il va déménager dans le dépot de simplon.co dans quelques jours...
@+

**Comment by dtarcz** [comment]
Il te semble bien :)
Ben si je suis "présent", non?
OK, merci Nico :) à plus alors.
